/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorIndexRouteImport } from './routes/editor/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as EditorSlugRouteImport } from './routes/editor/$slug'
import { Route as ArticleSlugRouteImport } from './routes/article/$slug'
import { Route as ProfileUsernameFavoritesRouteImport } from './routes/profile/$username.favorites'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorSlugRoute = EditorSlugRouteImport.update({
  id: '/editor/$slug',
  path: '/editor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameFavoritesRoute =
  ProfileUsernameFavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => ProfileUsernameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/editor/$slug': typeof EditorSlugRoute
  '/profile/$username': typeof ProfileUsernameRouteWithChildren
  '/editor': typeof EditorIndexRoute
  '/profile/$username/favorites': typeof ProfileUsernameFavoritesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/editor/$slug': typeof EditorSlugRoute
  '/profile/$username': typeof ProfileUsernameRouteWithChildren
  '/editor': typeof EditorIndexRoute
  '/profile/$username/favorites': typeof ProfileUsernameFavoritesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/editor/$slug': typeof EditorSlugRoute
  '/profile/$username': typeof ProfileUsernameRouteWithChildren
  '/editor/': typeof EditorIndexRoute
  '/profile/$username/favorites': typeof ProfileUsernameFavoritesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/article/$slug'
    | '/editor/$slug'
    | '/profile/$username'
    | '/editor'
    | '/profile/$username/favorites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/article/$slug'
    | '/editor/$slug'
    | '/profile/$username'
    | '/editor'
    | '/profile/$username/favorites'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/article/$slug'
    | '/editor/$slug'
    | '/profile/$username'
    | '/editor/'
    | '/profile/$username/favorites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  EditorSlugRoute: typeof EditorSlugRoute
  ProfileUsernameRoute: typeof ProfileUsernameRouteWithChildren
  EditorIndexRoute: typeof EditorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$slug': {
      id: '/editor/$slug'
      path: '/editor/$slug'
      fullPath: '/editor/$slug'
      preLoaderRoute: typeof EditorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/favorites': {
      id: '/profile/$username/favorites'
      path: '/favorites'
      fullPath: '/profile/$username/favorites'
      preLoaderRoute: typeof ProfileUsernameFavoritesRouteImport
      parentRoute: typeof ProfileUsernameRoute
    }
  }
}

interface ProfileUsernameRouteChildren {
  ProfileUsernameFavoritesRoute: typeof ProfileUsernameFavoritesRoute
}

const ProfileUsernameRouteChildren: ProfileUsernameRouteChildren = {
  ProfileUsernameFavoritesRoute: ProfileUsernameFavoritesRoute,
}

const ProfileUsernameRouteWithChildren = ProfileUsernameRoute._addFileChildren(
  ProfileUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  EditorSlugRoute: EditorSlugRoute,
  ProfileUsernameRoute: ProfileUsernameRouteWithChildren,
  EditorIndexRoute: EditorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
